### ISSUE TITLE
Possible problem with "Agent" field_linked_agent

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#104]
The core drupal system allows for selection of each field for various view types (like "Full", "Teaser", and in this case, the "Search result highlighting input" view mode for this content type).

The problem comes when we want to display ONLY the "Contributor" role agent (relators:ctb|Contributor) -- yet I believe that ALL Agent roles will be rendered in the search results.

**Comment by elizoller** [comment]
are you talking about in search results or in node display?

**Comment by elizoller** [comment]
you're correct if you just say display the linked agent field (in search results or node view), it will display all roles. i previously worked on a solution to index each role separately. by indexing it separately, when displaying the search results, it can be displayed separately - it doesn't however create a separate field for the typical node display.  i did it for the thesis advisor and author roles because i know those will be ones to commonly separately display. there are hundreds or marc relators/roles that a contributor can have so i didn't go through the trouble (yet) of duplicating this for all of those. a large chunk of the work is done in this commit: https://github.com/asulibraries/islandora-repo/commit/884ef3d6786a061874a4dc80a1747edc5ff4d80d

**Comment by wgilling** [comment]
closing the issue because it was my assumption that the Contributor would be needed all by itself on the item page, but "all contributors" should be displayed there.
