### ISSUE TITLE
Make RRSSB use Font-awesome icons via classes

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#117]
instead of overriding CSS

**Comment by wgilling** [comment]
twig added to our asulibs_barrio so that the rrssb button list is overridden so that we can switch that out to use the font awesome classes.

The module code was also edited so that the Permalink image uses the font awesome class as well - and changed the html so that the word Permalink is rendered as a link to that link.

**Comment by elizoller** [comment]
can i assume this is here: https://github.com/asulibraries/islandora-repo/tree/share_buttons_fontawesome ?
and do you want me to merge it in? i saw comments about the paragraph title display so i wasn't sure.

**Comment by wgilling** [comment]
yes - that's it - even thought I reset and fixed one more thing and push --hard --- I should have mentioned the branch name here.

Hopefully we can close this after it merges.

**Comment by elizoller** [comment]
ok, i'll take a look at it later today

**Comment by elizoller** [comment]
<img width="333" alt="Screen Shot 2020-08-05 at 10 43 09 AM" src="https://user-images.githubusercontent.com/5439169/89445817-7de39b00-d708-11ea-99ba-43c61e343337.png">
is this what i'm supposed to see?

**Comment by wgilling** [comment]
I only coded it to handle the buttons that appeared on the wireframes (facebook, twitter, email, and print) -- I am not sure if this needs to really handle all of the buttons at this point in time because some of the mappings from a share button to a font-awesome class are from the "Brands" subgroup and need a special class of "fab" while most of them are not and only need the additional class of "fa".


Will we want to have ALL buttons mapped to classes -- if not, do we need the two buttons that you have added?

**Comment by elizoller** [comment]
so i managed to mess up my config locally, huh? i'll check the wireframe and see if i can get that sorted. thanks
