### ISSUE TITLE
Visually Distinguish Entity State

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#128]
It would be nice to have visual distinction of when an entity is unpublished. 
In most cases this would be as simple as applying some styling on classes like `node--unpublished` 
It would also be nice to have a visual indicator for embargoed content - perhaps an icon for this

**Comment by elizoller** [comment]
Notes from design:
Unpublished state
-Collection
—Icon and text at top
—Color blocking title background
-Item
—Same as above
-Icon choice: Lock
- Files
—Do like legacy repository
—Circle with slash icon and a link to sign in

**Comment by wgilling** [comment]
We will need to revisit this in order to add logic that restricts access on some objects to collection-owners or specific roles.

**Comment by wgilling** [comment]
NOTES: 
1. some views do not allow admin to see the objects that are not published because the filter is set to `status = "Published"` but they would need `status = "Published" or admin`
2. "Latest additions" code (not a view) will not display items that are in the Archived state -- only Published here as well.
