### ISSUE TITLE
Self deposit UI

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#129]
The IR will need to provide a way for the user to self-submit their own content.

See the Self Deposit UI document: https://docs.google.com/document/d/1lo8W3CZvLH1kow_Dtr_NcgN2AxdkD9RBcq3BUAyD2yg/edit

The complex title should not be provided to these users -- instead, they would enter the Title value and the metadata folks would fix it by populating the Complex title.

Also, the code should redirect to the node/{nid}/media/add, to hide some fields -- as well as to provide specific values for some fields.

This can all be done with a new Form mode and handling the hooks to form_alter and submit.

The workflow would need to handle these cases of "self submitted content"

**Comment by elizoller** [comment]
We also discussed perhaps using a Form mode on the media (as well as on the node) to hide fields there as well.
We'll also want to behind-the-scenes set the "media use" to original file to avoid displaying one confusing field to the user.
On the node title, I might suggest that we use the Complex Title (paragraph) but we only display the "main" part of the title and hide the nonsort, subtitle, and supplied. Because we're using auto_entitylabel to populate the system title from paragraph complex title.

**Comment by wgilling** [comment]
It seems that there are several modules in the contrib that handle some part of our needs:
https://www.drupal.org/project/form_mode_manager (1,461 sites)
https://www.drupal.org/project/form_mode_control (294 sites - not stable release)
https://www.drupal.org/project/form_mode_routing (61 sites - not stable release)

Even though they are both in do not handle the entire usecase, I am going to test these contrib modules separately.

**Comment by elizoller** [comment]
form_mode_manager seems like it might help in terms of providing some UI elements and routes to get to the view modes. and it has  access control as well. the youtube they linked on the module page was helpful (although i recommend watching on 2x speed...) https://www.youtube.com/watch?v=7xFmSKNkRbo&feature=youtu.be

**Comment by elizoller** [comment]
well we've got a start now - closing this ticket as the base functionality is there and we can add additional tickets for more features related to this
