### ISSUE TITLE
Bulk update via XML

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#13]
Use Case: As a metadata manager/cataloger/administrator, I want to bulk export and import batches of legacy metadata (in multiple formats such as XML, RDF, and/or spreadsheet, etc. if possible) so that the metadata can be efficiently batch edited, normalized, transformed, etc. and re-ingested into the repository.

**Comment by elizoller** [comment]
bulk edit via UI can supposedly be achieved via  https://www.drupal.org/project/views_bulk_edit and https://www.drupal.org/project/views_entity_form_field

**Comment by elizoller** [comment]
Since metadata team prefers to work in a bulk sense in MODS XML instead of CSV, the migration of MODS XML referenced in #11 would also work for updating existing records as long as the node id matched.

**Comment by elizoller** [comment]
ultimately #11 will probably be the same thing

**Comment by wgilling** [comment]
So, do we want this to give the ability of users with a certain role to go into the website and go to a specific "MODS import / update" form and let the user upload a single MODS or modsCollection XML that will in turn execute the `drush migrate:import migrate_plus.migration.mods_xml.yml` using the url that points to the uploaded XML? I assume this code would also have to template to provide values for the migration's id: p_c284_node
label, and migration_group (like id: **p_c284_node**, label: **Import Collection 284 from CSV**, migration_group: **migrate_c284_csv**).

**Comment by wgilling** [comment]
I missed the details that were in issue #11 about how that would use the migrate_source_ui module to allow uploading and handle most of what we need to do here.

**Comment by wgilling** [comment]
The possibility of creating duplicate content with the single mods_xml migration is a slight concern since there is no way to provide a warning when a user is trying to update a node vs creating a new node, and they upload an XML file that does not contain the aztes value (in the recordInfo/recordIdentifier[@src="aztes"] node).

I proposed rebranding the mods_xml as "mods_xml_update" and adding a second instance of the same migration except that this one does not have the "skip_on_empty" for the nid field (so it would fail if using the update and the aztes is missing). This second instance could be called mods_xml_create.

**Comment by wgilling** [comment]
The previous commit includes a patch (web/modules/custom/asu_migrate/source_ui_url.patch) that could address the migrate_source_ui issue "JSON and XML migrations not being detected?" https://gitlab.com/drupalspoons/migrate_source_ui/-/issues/16
