### ISSUE TITLE
Landing page site

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#147]
This should be able to run the bento search on the KEEP and the [digital collections] site as well as the Legacy Repository, and Dataverse.

Not sure if it makes sense to have a playbook to spin this site up, but it will need at least:
- repo_bento_search module
- asulib_barrio subtheme

The DNS for the various sites would be as follows:
- Keep - keep.lib.asu.edu
- Digital collections - whatever.lib.asu.edu
- Repository landing page - repository.lib.asu.edu
- Legacy repository - stays at repository.asu.edu

**Comment by elizoller** [comment]
the site has been deployed, just need to finish a few more things
- [ ] static content and homepage text and hero
- [ ] recent and featured items/collections blocks

**Comment by dflitner** [comment]
Some nitpicky-ish styling things (from top to bottom). * items should carry over to the other sites

- [ ] Padding around main menu links should be 21px 25px or close to it. *
- [ ] Hover effect on main menu links (gold text, black background) *
- [ ] Suggest making search box `padding: 30px 15px` and `border-radius: 0`, remove the padding between the elements and I suggest making it full-width in that box. Maybe col-md-2 for the button instead of 3? Check with Jordyn on this.
- [ ] Welcome h2 `margin-bottom: 1rem`
- [ ] Welcome text box `padding: 2.5em 15px; margin-bottom: 4rem`
- [ ] Buckets - there's some phantom whitespace which is kind of ok because it's creating space but I'm a little worried about relying on it. So if we get rid of that and do margin on the headings, that would be better.
- [ ] `.repo-bucket-img img { margin-bottom: 15px; }`
- [ ] Double-check with Jordyn on this because the wireframe has some padding but she might not actually want it - p in the buckets `padding: 0 15px;` Might look ok if we add a border around the buckets.
- [ ] Footer links (icons and text) hover `color: $white;` *

**Comment by elizoller** [comment]
can access api like http://localhost:8000/api/recent?_format=json&type=asu_repository_item (type is option, default is asu_repository_item, can also use collection)

**Comment by dflitner** [comment]
Cards are to be styled like WS2.0 cards. See [WS 2.0 component XD](https://xd.adobe.com/view/a17f5adf-e8c4-4a86-530f-7cbaf6d17327-d74e/screen/95a9c9a3-0567-47c4-bc28-fe84d9d02d78/)

**Comment by dflitner** [comment]
Jordyn has requested we remove gray background from the welcome text on umbrella page.

Also need more space below the cards before the next heading.

**Comment by dflitner** [comment]
I removed the gray-bg class from the welcome box on umbrella page and the above commit comments out the extra padding.
