### ISSUE TITLE
Search within a complex object

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#180]
Add a search within a complex object to the sidebar
Should be similar to search within a collection but just has a filter for the single parent of the complex object parent

**Comment by wgilling** [comment]
This enhancement required an additional CSS class to pad the search form content in a sidebar block, so `gulp` will need to be run after pulling in this code.

It is a work in progress and has not been tested extensively, but so far it looked like it worked similarly to the Collection search. There may be a place where the word "Collection" appears instead of "Item" (like "Collection search results" instead of "Item search results" for the breadcrumb).

**Comment by wgilling** [comment]
code developed to provide a search form in the "Explore this item" sidebar block and corresponding search view display. The breadcrumb in that page is: **Search for: "SEARCH TERMS"**

Remaining issues:
1. configure facets for the search results view display page
2. potentially change the filter text and the link in "Explore this item" to do the search page with no filtering that would provide above mentioned faceting abilities "Explore items" (could possibly be "Explore media")

**Comment by wgilling** [comment]
![Screen Shot 2021-01-11 at 3 25 38 PM](https://user-images.githubusercontent.com/19391126/104245357-57492f00-5421-11eb-9ca7-1937fc1709bb.png)

**Comment by wgilling** [comment]
![Uploading Screen Shot 2021-01-11 at 3.27.36 PM.png…]()

**Comment by wgilling** [comment]
![Screen Shot 2021-01-11 at 3 44 02 PM](https://user-images.githubusercontent.com/19391126/104246808-dd667500-5423-11eb-80c2-b4d10ac5b92f.png)

**Comment by wgilling** [comment]
adjustments made to the config, code, and the complex title block as well in order to adjust it on the search page.

**Comment by elizoller** [comment]
closed with https://github.com/asulibraries/islandora-repo/pull/276
