### ISSUE TITLE
Add sidebar blocks to Full Metadata page

### ISSUE THREAD

**Issue by dflitner** [asulibraries/islandora-repo#187]
I have styling and a template for the full metadata view mode but it might need further tweaking after the blocks are added. I can't see how to make them show up on this page.

**Comment by elizoller** [comment]
can you add them via the block layout?

**Comment by elizoller** [comment]
ah i see, it breaks things. i'll look at it

**Comment by dflitner** [comment]
I don't think so. According to the block layout, they should be there already.. I think.
It says "display these blocks on ASU repository item content types, except on the edit or add node pages".

**Comment by elizoller** [comment]
except drupal doesn't know that `/items/nid/full-metadata` is a view of the asu_repository_item content type.

**Comment by dflitner** [comment]
That's what I figured was happening. I think there should be a way to specify that when you build the page in the module.

**Comment by elizoller** [comment]
i think so, i'm looking into that

**Comment by dflitner** [comment]
Full metadata display branch https://github.com/asulibraries/islandora-repo/tree/metadata-page

**Comment by elizoller** [comment]
oh...this opened a big can of worms

**Comment by dflitner** [comment]
uhoh what happened?

**Comment by elizoller** [comment]
turns out a bunch of the blocks and controllers relied on the parameter being an id, not a node and when i got the routing config correct to be a real node, it broke the contexts which determine the view modes. i'm still working through all of it....

**Comment by elizoller** [comment]
🔥 🔥

**Comment by elizoller** [comment]
Apparently in the routing you can just use `_entity_view` to send an entity route to a particular view mode. that's super helpful for a simple case where one route always goes to the same view mode (like the full metadata one). but we still need a custom controller for determining the view mode conditionally. and the custom controller wasn't getting picked up in the right order with the contexts. turns out we needed an event subscriber.
