### ISSUE TITLE
Make About a dropdown in the new ASU header/footer

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#289]
see: 
https://unity.web.asu.edu/@asu-design-system/bootstrap4-theme/?path=/story/components-global-header--basic
for proper behavior/styling

**Comment by elizoller** [comment]
@dflitner i noticed the library website has dropdowns now. is there some wisdom you can share on that?

**Comment by dflitner** [comment]
D7 sites have dropdowns due to the configuration of the ASU Component Header module which pulls in the Preact header and builds a menu to inject. And then I did some CSS nonsense to fake multiple columns.

I still need to configure the D8 menu macro to output the correct code for WS 2.0. It's next on my list to do.

**Comment by elizoller** [comment]
ah ok. no rush, i was just wondering since i noticed it on the lib website.
