### ISSUE TITLE
Comments enabled where they shouldn't be

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#291]
Comments are enabled in KEEP on basic pages - they should not be.

**Comment by wgilling** [comment]
This is actually set to display on Article pages. The plan is to just delete the comment field on Articles.

**Comment by wgilling** [comment]
There are no article pages in PRISM, but the configuration change can be applied to all sites so that none of them would have comments available even if somebody decided to create an Article.

**Comment by wgilling** [comment]
Removing the comments field from the Article content type.

**Comment by wgilling** [comment]
Since this change will require updating 7 configurations and deleting two of them, it would require a full import of config in order to achieve that... so it seems that doing it manually is likely preferred. To remove the comment field from the sites, log in as an administrator and navigate to the article content type | Manage fields section. From there, select the Delete option for the comment field.

Updated configs:

- core.entity_form_display.node.article.default.yml
- core.entity_view_display.node.article.search_index.yml
- core.entity_view_display.node.article.content_browser.yml
- core.entity_view_display.node.article.search_result.yml
- core.entity_view_display.node.article.default.yml
- core.entity_view_display.node.article.teaser.yml
- core.entity_view_display.node.article.rss.yml

Deleted configs:

- field.field.node.article.comment.yml
- field.storage.node.comment.yml

**Comment by elizoller** [comment]
we can use drush to delete the configs and import the updated ones and it should work without having to do a full config:import.
have you already done this change in keep prod?

**Comment by elizoller** [comment]
couldn't we just have removed comments from the article display mode?

**Comment by wgilling** [comment]
I have not touched the node in Prod. Like you said, if you delete the 2 configs and can run the config import on the 7 updated yml files, the node can remain as it is in Prod (an Article instead of a Basic Page).

After updating the configs as above, just confirm that the https://keep.lib.asu.edu/about/openaccess page does not have a comments section. I have done this in my VM and the configs make the comment disappear on an Article that previously displayed them when in the `develop` branch.

I am going to make this a Pull Request. There is nothing else about it that needs done.
