### ISSUE TITLE
Merge islandora_tokens with Jonathan Hunt's version

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#346]
There are two distinct modules named "islandora_tokens". Ours was written to populate the Google Scholar fields while Jonathan Hunt's version https://github.com/kayakr/islandora_tokens has a few other fields.

This should be put into the Controlled Access Terms module.

After completion, the old issue #94 Google Scholar settings may need to be reconfigured in order to use the new tokens (assuming that the name of the token would change).

**Comment by elizoller** [comment]
this is replaced by #364

**Comment by elizoller** [comment]
Wrong issue

**Comment by elizoller** [comment]
this is pending PRs in islandora community

**Comment by elizoller** [comment]
looks like these are down to PHPCS issues...so close!

**Comment by elizoller** [comment]
1 out of 2 of the PRs has been merged!

**Comment by elizoller** [comment]
There is a little bit of conflict/confusion with #238 on the second PR for controlled_access_terms. The PR for controlled_access_terms (and how we have our custom islandora_tokens module right now) splits agent names on the comma and reverses the order. In order to not manipulate the values, a patch is needed for metatag in order to set the value to delimit multiples on. So if we patch metatag via composer, we can remove the part with the manipulation of the names but it requires changing the way names are put together (ie. with a "|" instead of a ",") and also setting that config value in the metatag settings. This is straightforward, but it gets more complicated by the fact that we're pushing this work up to the islandora community and that the patch for metatag is still pending and islandora itself does not typically run with patches. Long story short... @wgilling is going to bring this to a future tech call. and it may be that we decide to take the patch locally even if islandora itself doesn't do that.

**Comment by elizoller** [comment]
@wgilling 👏 all your PRs have been merged. i think the last part of this ticket will be to decommission out own islandora_tokens module or to strip out the parts that will be covered by islandora and controlled access terms now and to update any configurations (if even necessary)

**Comment by wgilling** [comment]
All of the configuration values that are stored for the Google Scholar metadata have the same exact names with the code in the new places, so no configuration updates would be needed after uninstalling and removing the modules/custom/islandora_tokens module.

**Comment by elizoller** [comment]
i think this can be closed since both of the PRs have been merged and we now have  #460 and #238
