### ISSUE TITLE
Convert "Included in this item" to a view

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#355]
"Included in this item" is a hard-coded block. it'd be best if this could be a views block, much like how other areas of the site function. one "bug" i ran across with this view is that it does not reflect the "weight" field for the ordering of child items.

**Comment by wgilling** [comment]
While investigating this, I took a closer look at the islandora_core_features view "Manage members" and noticed that the query that was in there was using an OR condition on the node's langcode matching the parent langcode OR that the child has bundle of "islandora_object". Well, we do not use the content type of "islandora_object" and instead use our own "asu_repository_item" content type... so, as long as the langcode is not going to be different for any children the view could still work for us.

The query that this view uses is something like :
```
SELECT "node__field_weight"."field_weight_value" AS "node__field_weight_field_weight_value", "node_field_data"."nid" AS "nid"
FROM
{node_field_data} "node_field_data"
LEFT JOIN {node__field_member_of} "node__field_member_of" ON node_field_data.nid = node__field_member_of.entity_id AND node__field_member_of.deleted = '0' AND (node__field_member_of.langcode = node_field_data.langcode OR node__field_member_of.bundle = 'islandora_object')
LEFT JOIN {node__field_weight} "node__field_weight" ON node_field_data.nid = node__field_weight.entity_id AND node__field_weight.deleted = '0' AND (node__field_weight.langcode = node_field_data.langcode OR node__field_weight.bundle = 'islandora_object')
WHERE (node__field_member_of.field_member_of_target_id = '5626')
ORDER BY "node__field_weight_field_weight_value" ASC
LIMIT 11 OFFSET 0
```

This does not impact the page display that we have coded in asu_item_extras that uses a slightly different route (items/{nid}/members vs node/{nid}/members) because our code runs a query that is built in the model function asu_item_extras_get_complex_object_child_nodes.
