### ISSUE TITLE
Figure out how to handle remote video files

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#378]
an example: https://keep.lib.asu.edu/items/126594
i think we should be able to handle this with the drupal-provided remote video option, but the issue is that the media type doesn't have the necessary "islandora" fields like media of. so we'd need to modify for that.

**Comment by elizoller** [comment]
```Notice: Undefined index: remote_video in Drupal\islandora_matomo\IslandoraMatomoService->getFileFromMedia() (line 208 of /var/www/html/drupal/web/modules/custom/islandora_matomo/src/IslandoraMatomoService.php)```

**Comment by elizoller** [comment]
example: https://keep.lib.asu.edu/items/126704

**Comment by wgilling** [comment]
There was one issue with the RipRap code in trying to access the media object's related entity. That was able to be patched in a harmless bit of code that checks whether or not the entity exists before trying to use the media's file entity's methods.

The other issue is with the Matomo code. This is potentially a problem in the ability of Matomo to reflect any views for that media's "file" since it is external on YouTube (likely) and that system's traffic is not able to be tracked in Matomo. At the moment, I do no think that this is a problem, but I think I remember reading about a matomo class that can be added to the link so that it will increment the views for that item when clicked.... (possibly only related to the download of files, but need to look into this), so if this class can be added to external video links, then theoretically it could add the view when clicked.

**Comment by elizoller** [comment]
I think we're ok not to count any matomo views or downloads for the external links.
