### ISSUE TITLE
Content Change Digest

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#4]
Metadata Use Case #12 - As a metadata manager and a cataloger, I want to be regularly notified of all legacy metadata records that are edited, modified, etc. using the Repository metadata editing function/tool within a given period of time (once per day?). This would be similar to a daily digest via email, RSS, etc

Likely [message](https://www.drupal.org/project/message) and related modules can get us most of the way there on this one.

**Comment by elizoller** [comment]
@wgilling this might also be a good one?

**Comment by wgilling** [comment]
my thoughts initially are that this might be able to be handled with a couple Drupal core compents -- namely the current flavor of the old Drupal rules -- along with a Drupal view to define the changes over time and output that report to be sent as email body or something... will need to test this and confirm.

**Comment by wgilling** [comment]
After discussing the use case in more detail with Eli, the contents of the digest should include:
 - for added content: who added it, what time did they add it
 - for edited metadata: who made the edit, what time did they edit, what field value(s) changed from the former value(s)

For all objects referenced, the output should at least render a link to the object's metadata page.

**Comment by elizoller** [comment]
maybe this will help with the field value changes: https://www.drupal.org/project/diff
seems like you can make a view  of "Content revisions" - so maybe with the addition of the diff module could be added to that view?

**Comment by wgilling** [comment]
consider making the view into a REST Export and call this from a CRON to pass that json value into a twig template to make the HTML output and build an email to send to all the users of a specific role.

We should take a second look at the [Message](https://www.drupal.org/project/message) module.

**Comment by wgilling** [comment]
When there are changes to the binary files attached to any item, this it cannot be tracked by the diff module.

**Comment by wgilling** [comment]
The "Visual Inline" view mode for differences does not work with the current RDF settings on the ASU Repository Item.  Current view is using the "unified fields" view mode instead.

**Comment by wgilling** [comment]
The digest can use the Drupal maintenance cron to create and deliver the content change emailings.  Since this is a background task that Drupal does when anybody accesses the site, it would / could safely be skipped in the event where nobody accesses the site for a period of time (because NOTHING could change unless somebody accessed the site - except for in rare instances where REST updates are done, so this may be revisited to ensure that any change via REST would also count toward accessing the site).  Read more about Drupal maintenance cron here https://www.drupal.org/docs/user_guide/en/security-cron.html

**Comment by wgilling** [comment]
I feel that there may need to be a firm date range put on the view so that there is no gap when reporting as well as no duplicate reporting.

Currently the "-1 day" view has the filter on the Content Revision : changed value that is _greater than or equal to_ a value that is set to default of _current day -1_, but the view should probably have _between_ the `CCYY-MM-DD 00:00:00` (a) and `CCYY-MM-DD 00:00:00` (b) where (a) was yesterday's date.

**Comment by elizoller** [comment]
would the cron pass in the date its looking for?

**Comment by wgilling** [comment]
No, I can't imagine that it passes that -- rather the code itself would have to manage that by storing the "digest_run_timestamp" in a config variable and update it after each run so that it only runs once.

Do you have any better ideas as to where to store that value?

**Comment by elizoller** [comment]
how is the view invoked from the cron hook?

**Comment by wgilling** [comment]
I am working on that - I want to (cross my fingers) and get some of the bits that the Drupal conference presentation used for their emailings to do this part.

Considering this may take a bit of time to run (view query + generate the email + send to all recipients) and given that the drupal CRON is triggered by a user when they view any content (if it is overdue), that this should likely be set up to process on a linux crontab entry such as:
`30 * * * * web_user /var/www/html/vendor/bin/drupal --root=/var/www/html/docroot cron:execute > /dev/null 2>&1` _with the obvious edit to point to the correct root path_

Also, the hook_cron page https://api.drupal.org/api/drupal/core%21core.api.php/function/hook_cron/8.2.x mentions worker queues for doing any processing that may not be really quick.

**Comment by elizoller** [comment]
i see, so if it executes via crontab (what it calls manual cron vs automated cron) then you wouldn't have to worry as much about user interaction issues. i believe an example is provided in the d8 example module set of how you might change a specific cron task from executing on every cron run, see https://api.drupal.org/api/examples/cron_example%21cron_example.module/function/cron_example_cron/8.x-1.x

**Comment by wgilling** [comment]
THANKS -- this is exactly what I was envisioning having to write.

`  // We access our configuration.
  $cron_config = \Drupal::config('cron_example.settings');
  ... logic follows `

**Comment by elizoller** [comment]
it also has this piece 
``` // We usually don't want to act every time cron runs (which could be every
  // minute) so keep a time for the next run in the site state.
  $next_execution = \Drupal::state()
    ->get('cron_example.next_execution', 0);```
which might be helpful

**Comment by wgilling** [comment]
From an old thread RE Drupal 7: How to send a View in an email triggered by a rule - https://www.drupal.org/node/1078116

drupal_html_to_text() is no longer there is drupal8. Drupal\Core\Mail\MailFormatHelper::htmlToText() should be used instead.

**Comment by wgilling** [comment]
In the event that the view can not be used via the emailing module, the query behind the view is:
`SELECT node_field_data_node_field_revision__tracker_node.changed AS node_field_data_node_field_revision__tracker_node_changed, node_field_data_node_field_revision__tracker_node.nid AS node_field_data_node_field_revision__tracker_node_nid, node_field_data_node_field_revision.changed AS node_field_data_node_field_revision_changed, node_field_revision.vid AS vid, node_field_data_node_field_revision.nid AS node_field_data_node_field_revision_nid
FROM
{node_field_revision} node_field_revision
INNER JOIN {node_field_data} node_field_data_node_field_revision ON node_field_revision.nid = node_field_data_node_field_revision.nid AND node_field_data_node_field_revision.langcode = node_field_revision.langcode
INNER JOIN {tracker_node} node_field_data_node_field_revision__tracker_node ON node_field_data_node_field_revision.nid = node_field_data_node_field_revision__tracker_node.nid
WHERE (node_field_revision.status = '1') AND (node_field_data_node_field_revision.type IN ('asu_repository_item', 'islandora_object')) AND ((node_field_revision.changed >= 1585257809-86400))
ORDER BY node_field_data_node_field_revision_changed DESC, node_field_revision.changed ASC`

_of course, the value for the changed date comparison (1585257809 - 86400) should be parameterized_

**Comment by wgilling** [comment]
Since drupal EntityQuery does not support a "NULL" or "NOT NULL" condition, drupal.org/project/drupal/issues/1157006 I have to load all users by role and loop through to check the value of the custom "opt out of digest emails" field value.

**Comment by wgilling** [comment]
this is effectively done, but it may be nice to have a configurable email body prefix area that would be added to the top of the emailings.

All of the code is in the module content_change_digest and this is in the islandora_repo "content_digest" branch of the code until it can be merged.

**Comment by elizoller** [comment]
should i check out this branch and look at it for merging?

**Comment by wgilling** [comment]
This module depends on the views and handlers that come from the drupal/diff module. I need to get the diff module installed as part of this change - wouldn't that be a change to the claw-playbook code? Until that point in time, the diff module will need to be installed manually
```
$ composer require drupal/diff
# (if you run out of memory, you know what to do to the php.ini files)
$ cd web;drush pm-enable diff
$ drush updatedb;drush cr
```

The configuration `admin/config/content_change_digest/adminsettings` allows for selection of who should get the "Content Change Digest" by user name as well as by role. In the user's edit profile page, there should be a checkbox to allow them to opt-out of the content change digest emailings; this checkbox only displays for users who are currently configured to get the emailings (but that checkbox would disappear if the module configuration was changed).

Currently there is no way to check how frequently the drupal CRON is run -- the code is written to have a 24 hour period between cron executions -- this number should probably be configurable (easy to add this configuration)... but should the resolution be in hours / minutes or days? We may need to adjust the frequency with which the drupal cron runs.

Additionally, this module creates a view (with two pages - the default is 24 hour and a page that has the changed date exposed as a filter to the user to see "differences since XX date") `admin/structure/views/view/differences`) - the output of the first page of this view is what makes up the body for the emails.

Let me know if you have ANY questions whatsoever.

**Comment by elizoller** [comment]
I think having this email run once a day is what we've been asked for. But it is possible that we'll have cron running more frequently than that. Can we write it in a way that allows cron to run more frequently but this module knows to only fire off the emails at a particular hour or something?

**Comment by wgilling** [comment]
Yes - it is actually written that way -- and only executes the code to compose emails when the period of 86400 seconds has passed since the last run. I am sorry that I miscommunicated how the CRON schedule has a bearing on that.

**Comment by elizoller** [comment]
Excellent, thanks for clarifying

**Comment by elizoller** [comment]
This branch has been merged in as of https://github.com/asulibraries/islandora-repo/commit/ed95d505172e0386654a21180070d186de8ac55a
Yay @wgilling!!

**Comment by elizoller** [comment]
@wgilling - how do you feel about closing this and creating a new issue for theming/styling of the email?

**Comment by wgilling** [comment]
@elizoller - brilliant idea... I will create that new issue now - feel free to edit the new ticket.

**Comment by wgilling** [comment]
The metadata group would love to have the output to display both NEW content as well as revised content.

The links to the nodes should take the user to the Full Metadata page rather than the default view mode.

The approach would be to make a second view that only lists new content (content with no revisions) and pull in both views when composing the emailing... apply a little bit of logic to determine whether or not to display a message like:
New Content
---
There is no new content since the last digest was generated.

vs.

New Content
---
[view of all nodes that were created on the date -- and link them to the Full Metadata view]


It would also be nice if the email subject to include the date period of the digest.

**Comment by wgilling** [comment]
Should the emailing have the standard ASU header / footer contents? Not that I am trying to make things more difficult, but it may not be too difficult with Drupal to add the rendered footer to any HTML that is to be used for theming the emailings.

![image](https://user-images.githubusercontent.com/19391126/90429244-2df6c380-e07a-11ea-8319-9b07ebf7119d.png)
