### ISSUE TITLE
REST API for search

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#41]
can we just have a REST/JSON view of the search view?

**Comment by wgilling** [comment]
I do believe that would be easy to achieve by:

- add a new [REST export] display
- set the Format | Settings to "json"
- edit the path for this to be /solr-search-rest-api/content

I will test this and report back with the results.

Now, since the use case grouping for #41 (various search functionalities) does not reference any REST endpoint for search, I am not sure whether or not this use case needs to publish that API url anywhere or embed it in any HTML for the page like a <link rel=?? /> type of reference.

**Comment by elizoller** [comment]
The primary use case for this is that the Bento Beta Search (https://betasearch.lib.asu.edu/) uses the search API for the legacy repository (which is a simple shim through Django over the actual solr search). 
It'd be great if we could use REST export to accomplish that.

**Comment by wgilling** [comment]
cool - I had assumed it had something to do with one of our systems needing to support a legacy call.... and I'd like to see the requirements or detailed use case, yet I wondering in advance which authentication it would use if any:

-  basic_auth
-  jwt_auth
-  cookie

**Comment by elizoller** [comment]
It could use basic auth. We basically just need to support a basic keyword search, we use something like `https://repository.asu.edu/api/items/search?q=insert term here` and returns the solr search response for items that match that keyword.

**Comment by elizoller** [comment]
I'm not sure REST Export + Search content actually works today haha...

**Comment by elizoller** [comment]
maybe this module will help https://www.drupal.org/project/jsonapi_search_api its super beta though

**Comment by elizoller** [comment]
use like: http://localhost:8000/api/search?search_api_fulltext=test&_format=json

**Comment by wgilling** [comment]
does this endpoint have a "num results" parameter?

**Comment by wgilling** [comment]
looks like the call is actually using the parameter name q, like:
http://localhost:8000/api/search?q=work&format=json
