### ISSUE TITLE
Fix Copy Link Button

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#419]
<img width="818" alt="Screen Shot 2021-07-01 at 9 45 48 AM" src="https://user-images.githubusercontent.com/5439169/124160579-41700a80-da51-11eb-8849-51e467c63a61.png">

This needs to be one of the ws 2.0 round buttons and should probably be a small or medium one like `btn-maroon btn-sm`

**Comment by wgilling** [comment]
when using btn-md, the button text "Copy link" is wrapping unles the  div class that contains the input prompt from a col-9 to col-8.

 <img width="554" alt="Screen Shot 2021-07-01 at 3 35 55 PM" src="https://user-images.githubusercontent.com/19391126/124196837-0fc36780-da82-11eb-86b7-eb458d9a161f.png">

Also, in either the btn-sm or btn-md case, the link itself needs to be given a line-height CSS attribute so that it aligns the vertical centers with the text box to the left.
