### ISSUE TITLE
Add attributes to buttons for hover titles

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#500]
- copy citation
- permalink
- feedback
- search
- download

**Comment by wgilling** [comment]
While looking into this, I found that the Copy citation button no longer works at all. This is due to the fact that the input field has a Basic HTML input format and thus is being wrapped with <p> tags for each line entered. This has been addressed in the three separate twig files: field--node--field-preferred-citation.html.twig, field--node--field-preferred-citation--collection.html.twig, field--node--field-preferred-citation--asu-repository-item.html.twig.

Also, the "Permalink" link buttons already have a title that is set to the actual item handle value.

**Comment by wgilling** [comment]
I could not find a way to override or style the button that appears on the exposed form search form block... try to find a form preprocess hook that can do this
