### ISSUE TITLE
When viewing the admin taxonomy terms for Person, fatal error

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#520]
On KEEP, I wanted to view the existing Person taxonomy https://keep.lib.asu.edu/admin/structure/taxonomy/manage/person/overview routes and this happened. Other vocabulary seemed to load without any problems.

`InvalidArgumentException: The URI 'Enseble' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 291 of /var/www/html/drupal/web/core/lib/Drupal/Core/Url.php).
`

**Comment by elizoller** [comment]
a while ago i added a separate view (available here keep.lib.asu.edu/taxonomy-list-alternate/person) because the person taxonomy was so large that it was breaking. but this isn't that. 
I'm not able to replicate this particular error - are you still able to?
i just get out of memory on trying to load that page. (hence the alternate view...)

**Comment by wgilling** [comment]
I only see this error on KEEP and not in my local VM (I assume because of how many terms are local vs. in KEEP). The link that I have in the description of the issue is an internal link from the admin Taxonomies page. The admin page that I mention has no way to load this alternate view. As long as there is not an underlying issue with this vocabulary I guess it doesn't need to be a high priority. Maybe you can close this issue. (???)

**Comment by elizoller** [comment]
mysterious.... let's close for now and we can reopen if we run into it again
