### ISSUE TITLE
Video thumbnail derivatives not generating

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#569]
These have broken thumbnail icons: https://keep.lib.asu.edu/items/146348  https://keep.lib.asu.edu/items/145673, https://keep.lib.asu.edu/items/127438 https://keep.lib.asu.edu/items/127161 https://keep.lib.asu.edu/items/127520 https://keep.lib.asu.edu/items/127113 https://keep.lib.asu.edu/items/127063 

These two have broken thumbnail icons AND inoperable viewers: https://keep.lib.asu.edu/items/146708 https://keep.lib.asu.edu/items/146926

**Comment by seth-shaw-asu** [comment]
Circling back, the following have working thumbnails:

- https://keep.lib.asu.edu/items/146348
- https://keep.lib.asu.edu/items/127438
- https://keep.lib.asu.edu/items/127161 (MOV file without an MP4 derivative, but it is a large 3.8 GB file, so I'm not surprised.)
- https://keep.lib.asu.edu/items/127520

These two were PDFs where deleting the broken thumbnail and regenerating it fixed it:

- https://keep.lib.asu.edu/items/146708 (66.6 KB _PDF_)
- https://keep.lib.asu.edu/items/146926 (65.1 KB _PDF_)

These were also fixed by deleting the thumbnails and regenerating them.

- https://keep.lib.asu.edu/items/145673 (24.6 MB M4v original)
- https://keep.lib.asu.edu/items/127063 (1.6 GB MOV original)
- https://keep.lib.asu.edu/items/127113 (2.6 GB MOV original)
