### ISSUE TITLE
Derivative Issues.

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#580]
These items haven't generated derivatives in at least a day, so something seems to be wrong with them.
https://prism.lib.asu.edu/items/93684  https://prism.lib.asu.edu/items/93824 
https://prism.lib.asu.edu/items/93973 https://prism.lib.asu.edu/items/93985 https://prism.lib.asu.edu/items/94025 https://prism.lib.asu.edu/items/94028 https://prism.lib.asu.edu/items/94116 https://prism.lib.asu.edu/items/94187 https://prism.lib.asu.edu/items/94173 https://prism.lib.asu.edu/items/94300 https://prism.lib.asu.edu/items/94321 https://prism.lib.asu.edu/items/94342 https://prism.lib.asu.edu/items/94465 https://prism.lib.asu.edu/items/94680 https://prism.lib.asu.edu/items/94667 https://prism.lib.asu.edu/items/94670 https://prism.lib.asu.edu/items/94643 https://prism.lib.asu.edu/items/94721 https://prism.lib.asu.edu/items/94723 https://prism.lib.asu.edu/items/94724 https://prism.lib.asu.edu/items/94725 https://prism.lib.asu.edu/items/94726

**Comment by seth-shaw-asu** [comment]
Broken items that need to be fixed:
- https://prism.lib.asu.edu/items/93684 *bad PDF upload; needs to be replaced*
- https://prism.lib.asu.edu/items/94300 *Filename included an accented character which didn't play well with the system. Please delete the file and then rename the file and upload it again.*

Fixed by triggering the thumbnail derivative again:
- https://prism.lib.asu.edu/items/93824
- https://prism.lib.asu.edu/items/93973
- https://prism.lib.asu.edu/items/93985
- https://prism.lib.asu.edu/items/94028
- https://prism.lib.asu.edu/items/94116
- https://prism.lib.asu.edu/items/94321
- https://prism.lib.asu.edu/items/94342
- https://prism.lib.asu.edu/items/94465
- https://prism.lib.asu.edu/items/94680

Still pending; check back on these later:
- https://prism.lib.asu.edu/items/94025
- https://prism.lib.asu.edu/items/94187
- https://prism.lib.asu.edu/items/94173
- https://prism.lib.asu.edu/items/94667
- https://prism.lib.asu.edu/items/94670
- https://prism.lib.asu.edu/items/94643


We can't create thumbnails for Excel documents at this time.:
- https://prism.lib.asu.edu/items/94721
- https://prism.lib.asu.edu/items/94723
- https://prism.lib.asu.edu/items/94724
- https://prism.lib.asu.edu/items/94725
- https://prism.lib.asu.edu/items/94726
