### ISSUE TITLE
Collect and display statistics such as views, downloads of media/file

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#62]
how far can matomo get us for this?

**Comment by elizoller** [comment]
related: islandora issue 1381

**Comment by elizoller** [comment]
Need more clarity around what we need here. we could possibly use some custom google analytics tag trackers to track views/downloads/streams

**Comment by wgilling** [comment]
additionally, do we want only one count to account for all possible download sizes (for images)? I assume that we do want just one number in those cases. This topic was added to our Repo Dev meeting agenda for this week.

**Comment by elizoller** [comment]
i can see the value in having separate stats for each file - i wonder if matomo can give us any of this "out of the box"

**Comment by elizoller** [comment]
someone mentioned this module on islandora slack - maybe it'll be helpful for displaying statistics in the repo (not through the matomo interface which would only be selectively available) https://www.drupal.org/project/matomo_reports

**Comment by elizoller** [comment]
similarly - but more on the collection level - https://github.com/mjordan/islandora_repository_reports might be helpful from mark jordan

**Comment by elizoller** [comment]
We have added the https://github.com/asulibraries/islandora_matomo module for displaying the download count on the item page, we'll like need to build additional blocks/pages to accomplish collection level statistics.

**Comment by wgilling** [comment]
the last commit to add the collection download table to the collection statistics report does not support a CSV download (like the other two tables do) which may not even be required.

**Comment by wgilling** [comment]
Well, I feel that the downloads table may need to be truncated because the possibility of listing EVERY node of a collection in this table does not feel right. Since the table is populated with a function getCollectionDownloads in the statisticsReportController it is not super-friendly at this point to support pagination since the entire set of nodes need to be tabulated before they can be sorted by download count.

I am not sure if this would be easy to save into some sort of cache table upon calculation and then load these via ajax to support pagination - so that the work does not need to be done EACH time a new set of records need to be fetched.
![Screen Shot 2021-01-15 at 11 14 12 AM](https://user-images.githubusercontent.com/19391126/104763735-975f2900-5723-11eb-8da0-319eb9390347.png)

**Comment by wgilling** [comment]
perhaps it would be best to display the top 50 downloads and just stop there. I added this to the design agenda for Monday.

**Comment by wgilling** [comment]
If pagination is needed, I suppose that it would be pretty easy to make a summary table that stores a timestamp, collection id(), node id(), and downloads count --- for the purpose of supporting pagination. The primary key would be node id() and the table would be indexed on collection id() and downloads.

Step 1 would be to check for download summary records that exist from the last 15 or 30 minutes... and if not, calculate them... else, load the appropriate set of 10 or 20 records.

**Comment by wgilling** [comment]
from the design meeting:

- Add a “Download CSV” option for ALL records in the collection
- Store the results in a summary table and repopulate only when the cache for the page expires. (similar to how the Collection stats does this via a drush command that is triggered by CRON)
- Show the top 50 results of these

**Comment by wgilling** [comment]
The slow work of querying each item in a collection for the total downloads has been rewritten to an off-line CRON process. This is the same drush method that was previously only populating the asu_collection_extras_collection_summary values, but now it also populates the download counts in a separate table (since it was already looping through these items to sum the collection views before).

That drush command fails to load the downloads because the host value of the web site is not known and it was coming up with url values like http://default/sites/default/files/2021-01/3-Thumbnail%20Image.jpg instead of http://localhost:8000/sites/default/files/2021-01/3-Thumbnail%20Image.jpg -- so, this drush call must now provide the host value like this:
```1 0 * * * /usr/local/bin/drush --uri=http://localhost:8000/ asu_collection_extras:collection_summary >/dev/null 2>&1```

Of course, this CRON command will have to be adjusted for each website's host value like:
```1 0 * * * /usr/local/bin/drush --uri=https://repo-dev.aws.lib.asu.edu/ asu_collection_extras:collection_summary >/dev/null 2>&1```
```1 0 * * * /usr/local/bin/drush --uri=https://keep.lib.asu.edu/ asu_collection_extras:collection_summary >/dev/null 2>&1```

If the table does not exist for either the summary or the downloads, there will be a message added to watchdog for each instance where the code was going to use it. To create these tables, you can uninstall / install the asu_collection_extras module like:
```drush pm-uninstall asu_collection_extras; drush pm-enable asu_collection_extras```

If that is not possible, the new table can be created by running the SQL:
```CREATE TABLE `asu_collection_extras_item_downloads` (
  `collection_nid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The collection "node".nid this record affects.',
  `nid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The item "node".nid this record affects.',
  `views` int(11) NOT NULL DEFAULT '0' COMMENT 'View total for all objects in the collection.',
  `downloads` int(11) NOT NULL DEFAULT '0' COMMENT 'Download total for all objects in the collection.',
  PRIMARY KEY (`collection_nid`,`nid`),
  KEY `downloads` (`downloads`),
  KEY `collection_nid` (`collection_nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Store the # of downloads for each asu_repository_item'```

**Comment by wgilling** [comment]
Without too much trouble, the process for getting the download counts can be separated into its own drush method, but for simplicity's sake -- and since the summary is already looping over the same items to get the total views for the collection stats box, it was simply added to that method.

**Comment by elizoller** [comment]
Is this the code we need for this https://github.com/asulibraries/islandora-repo/compare/collection_downloads_62 ?
