### ISSUE TITLE
Fixity Check Improvements

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#82]
see previous ticket: https://github.com/asulibraries/islandora-repo/issues/51

After MVP
- parse out by collections or group of collections
- maybe install riprap as a separate user instead of root (fix cron run by root?)
- investigate hashing algorithms and implement the one of choice (compare speed?)

**Comment by wgilling** [comment]
Scalability of this service is a concern for me as the size of the repository grows -- especially at the point when there is enough content that the expectation period between checks can not be met.

There may be a way to deploy that work to multiple servers so that the number of CPUs that will be processing the checksums can grow as the repository grows.
