### ISSUE TITLE
Google Scholar Indexing

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#94]
@tallgood mentioned the need for IR content to be indexed in google scholar.
i'm linking in some related documentation: https://scholar.google.com/intl/en/scholar/inclusion.html#overview
https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

From that indexing page it appears that there are a few key pieces

1. each article has to have a separate HTML page or  PDF file (this should be fine since that's how content should be modelled anyway ... I assume these would need to be in the sitemap so I'm not entirely clear if that means each media object needs to be in the sitemap or each file or if we can get away with just the nodes)
2. required meta tags - there are quite a few specifics about this and I'm hopeful we'll be able to accomplish it through the metatag module but haven't attempted anything 
example here: 
```
<meta name="citation_title" content="The testis isoform of the phosphorylase kinase catalytic subunit (PhK-T) plays a critical role in regulation of glycogen mobilization in developing lung">
<meta name="citation_author" content="Liu, Li">
<meta name="citation_author" content="Rannels, Stephen R.">
<meta name="citation_author" content="Falconieri, Mary">
<meta name="citation_author" content="Phillips, Karen S.">
<meta name="citation_author" content="Wolpert, Ellen B.">
<meta name="citation_author" content="Weaver, Timothy E.">
<meta name="citation_publication_date" content="1996/05/17">
<meta name="citation_journal_title" content="Journal of Biological Chemistry">
<meta name="citation_volume" content="271">
<meta name="citation_issue" content="20">
<meta name="citation_firstpage" content="11761">
<meta name="citation_lastpage" content="11766">
<meta name="citation_pdf_url" content="http://www.example.com/content/271/20/11761.full.pdf">
```

3. correctly marking references in the PDF or in HTML - not sure on that one

**Comment by elizoller** [comment]
Perhaps this beta module will get us part/most of the way there on the metatag component: https://www.drupal.org/project/metatag_google_scholar

**Comment by elizoller** [comment]
I just mentioned this on another ticket but: https://www.drupal.org/project/metatag_google_scholar was plugged by seth recently and now has an official release.

**Comment by wgilling** [comment]
Configuration for the metatags for the asu_repository_item content type are here: 

This would use tokens to set the values for each of the metatags that are defined by the metatag_google_scholar module (fields defined as per the config/schema/metatag_google_scholar.metatag_tag.schema.yml file) yet some values may need additional format handling in order to populate.
![image](https://user-images.githubusercontent.com/19391126/96024836-26009900-0e09-11eb-8b0f-aec2da977b2b.png)

I believe we may need a couple custom token handlers to provide a specific Linked Agent value for something like “Author” and First/Last page (is this a numeric value or a link to that page?), and especially a PDF URL value… tokens seem like the way to go to query the provided object and return the desired values. The "Publication Date" would not take the `field_edtf_date` value since it is not formatted as it needs to be for Google Scholar.

**Comment by wgilling** [comment]
NOTE: quite a few of the "out of the box" Metatag Google Scholar fields that are available for the Google Scholar indexing since there seem to be no corresponding fields on the node that map to them, a token may need to be added in the future to parse those value (unless it is handled by the standard node tokens for those fields that are not managed by the islandora_tokens module). If these fields are added to our [asu_repository_item](http://localhost:8000/admin/config/search/metatag/node__asu_repository_item?destination=/admin/config/search/metatag) or [collection](http://localhost:8000/admin/config/search/metatag/node__collection?destination=/admin/config/search/metatag) nodes, the configurations for each of those would need to be adjusted to map either the node-field or the islandora_tokens-token that would have to be added to the code.

The unused fields that are available are:
> **Publication date** (collection is lacking, asu_repository_item uses node.field_edtf_date_created)
> **Journal title**
> **ISSN**
> **ISBN**
> **Volume**
> **Issue** ( node.field_series? see below )
> **First page**
> **Last page**
> **Dissertation Institution**
> **Technical report institution**
> **Technical report number**
> **PDF URL** (see below)

* In the case of the PDF URL, it could be that the code could look at our node's media to find a service file that is a PDF file and return the URL to view or download this.

* I believe that the field_series may be used for the Issue configuration at http://localhost:8000/admin/config/search/metatag/node__asu_repository_item?destination=/admin/config/search/metatag by mapping this token to output the node.field_series field.

In the case of several of these fields, we may really want to start including them if possible. Perhaps this list above should be reviewed and even sent to the metadata team and then discussed for considerations.

Also NOTE that since the Created Date is an EDTF field and there is some form-level validation going on that does not allow all possible EDTF formats (such as "Spring, 2004" or "1990s"), I have added exception handling to the token processor for the `publication_date` (field_edtf_date_created) and it would be logged in the watchdog logs.

The testing value that I was able to see the exception being handled (and was not forbidden by the form-level validation) was field_edtf_date_created = "~2001".

**Comment by wgilling** [comment]
For a date value that is only 4 digits, the code below would fail to get a DateTime object that has that value and was returning the current date (as if called with 'now' as the value) instead.

        $v = $created_date->getValue($field_name)[0]['value'];
        $date_val = new DateTime($v);

So, as a result, I check that the length is at least 6 digits and throw an exception instead ([see code](https://github.com/asulibraries/islandora-repo/commit/ac5d1dcbc1813718c78e956763e80c28e989efb9#diff-bd3c5bcc562334d600a90cb23884cf50b707e62cb3beeba1946c6c2d031a823fR133-R138)). THIS MAY NOT BE THE BEST WAY to skip returning the current date value.
